# This is a basic workflow to help you get started with Actions

name: test-units

# Controls when the action will run.
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "main"
  main:

    strategy:
      matrix:
        python-version: ['3.7']
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Dependencies
        run: |
          python -m pip install pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          sql-pass: ${{ secrets.SQL_PASSWORD }}
          sql-user: ${{ secrets.SQL_USER }}
          sql-db: ${{ secrets.SQL_DB }}
        run: |
          pytest
